draw_rectangle_color(0, 0, 480, 60, c_black, c_black, c_black, c_black, 0);
draw_set_font(fnt_bigsans);
draw_set_halign(fa_center);
draw_set_valign(fa_top);
draw_text(240, 0, "SCORE:" + string(global.gamescore));
draw_set_font(fnt_smallsans);
var highscoreadd = string(global.gamescore - global.highscore);
draw_text(240, 40, "HIGHSCORE:" + string(global.highscore) + (global.gamescore > global.highscore ? (" + " + highscoreadd) : ""));
draw_sprite_ext(spr_tailslives_icon, obj_exe.gotime, 40, 10, 2, 2, 0, c_white, 1);
draw_text(50, 40, "HEALTH:" + string(global.lifes));
draw_text(400, 40, global.seconds < 100 ? "TIME LEFT:" + string(100 - global.seconds) : "RUNRUNRUN");