palselect = 0;
test = 0;
espeed = 0;
hsp = 0;
vsp = 0;
grav = 0.4;
landed = 0;
gotime = 0;
xscale = 1;
yscale = 1;
alpha = 1;
randomize();
jokevoiceline = irandom_range(1, 100);
flowery = irandom_range(-50, 1);
exe = !variable_global_exists("exe") ? "S" : global.exe;
ini_open("gameData.ini");
global.exe = ini_read_string("exeinfo", "exechar", "S");
global.exepalette = ini_read_real("exeinfo", "exepalette", 0);
ini_close();
GMScript_exespr();
exe = global.exe;
GMScript_exespr();
palselect = global.exepalette;
paltoselect = global.exepalette;
exenum = 0;
exename = ["2011X", "ROBOTNIK", "FLOWERY"];
palettename = ["THE ONE AND ONLY", "BIT BLUE TODAY", "THESE SOULS ARE\nTURNING MY QUILLS GRAY!", "I'M NICE...", "ORANGE PUNCHER", "CENSORED FOR YOUTUBE:)", "X1102", "AN ODE TO THE FOX", "HE'S SO FUCKING BLUE", "PALE X", "SUPER X", "BLOOD COVERED", "MARIJUANA X", "RED HOT X", "POLYESTER X"];
pal_swap_init_system(shd_pal_swapper, shd_pal_html_sprite, shd_pal_html_surface);
if instance_exists(obj_tails)
	depth = obj_tails.depth - 1;