pal_swap_init_system(shd_pal_swapper, shd_pal_html_sprite, shd_pal_html_surface);
bg0x = 0;
bg1x = 0;
bg2x = 0;
bg3x = 0;
bg4x = 0;
bg5x = 0;
groundx = 0;
palselect = 1;
reverse = 0;
obstaclearray = [obj_evilwhiteball, obj_groundpillar, obj_rock];
enemyarray = [obj_fuckingball, obj_sharkguy, obj_spikes, obj_spikeball];
alarm[1] = 5;
alarm[0] = 150;
alarm[3] = 50;
alarm[2] = 1;
fireef = 0;
burning = 1;
ini_open("gameData.ini");
global.name = ini_read_string("playerinfo", "name", "");
ini_close();
gonermaker = 0;
keyboard_string = "";