pspeed = 1;
hsp = 0;
vsp = 0;
grav = 0.4;
rolling = 0;
jumping = 0;
tails = 0;
palselect = 0;
state = 0;
dead = 0;
highscorebeat = 0;
halfscore = 0;
tailrot = 0;
keyjump = 0;
keydown = 0;
keyjump2 = 0;
keydown2 = 0;
jumpbuffer = 0;
downbuffer = 0;
powerup = 0;
shield = 0;
shieldspr = spr_null;
bubbled = 0;
flamed = 0;
thundered = 0;
y = 206;
global.gamescore = -1;
global.lifes = 10;
pal_swap_init_system(shd_pal_swapper, shd_pal_html_sprite, shd_pal_html_surface);
ini_open("gameData.ini");
global.highscore = ini_read_real("game", "highscore", 0);
ini_close();